Linkedin Company Integration
alvwin/ai_phishing_toolkit pull request #5
Opened 2024-09-05 13:02 UTC by manudev-1

# Description of the PR

This pull request integrates **LinkedIn Company** as a possibility for the user. The integration allows the project to create prompt based on LinkedIn Company giving the name.

## Changes Made

- Added 4 public function in `LinkedinService` to manage company data
- Added 4 private function in `LinkedinService` to manage and parse company data

2024-09-05 17:11 UTC, alvwin commented on SocialService/Social/LinkedinService.py
> +        print("\n\nPlease enter the user ID of the user you would like to scrape:")
Gotta change this to be correct for the company

2024-09-05 17:11 UTC, alvwin commented on SocialService/Social/LinkedinService.py
> +        print("\n\nPlease enter the path to the file containing the list of usernames you would like to scrape:")
here as well `Please enter the path to the file containing the list of companies you would like to scrape:`

2024-09-05 17:12 UTC, alvwin commented on SocialService/Social/LinkedinService.py
> +                print(f"{Const.COLOR_ERROR}User {user_id} not found{Const.RESET_ALL}")
And here

2024-09-05 17:17 UTC, alvwin requested changes
Needs a few changes in console outputs and i haven't had the time to test it yet

2024-09-06 09:26 UTC, manudev-1 commented
> Needs a few changes in console outputs and i haven't had the time to test it yet

I will apply the changes that you suggest

2024-09-06 10:52 UTC, alvwin reviewed
Still need to test but code looks good

2024-09-06 10:52 UTC, alvwin approved these changes

2024-09-06 11:43 UTC, manudev-1 commented
> Still need to test but code looks good

Yeah, sure no problem, take your time

2024-09-06 21:36 UTC, alvwin requested changes

2024-09-06 21:36 UTC, alvwin commented on Util/Const.py
> +    account_type_options_list = ["User", "Company"]
needs an company_options_list "single company" and "multiple companies"

2024-09-06 21:36 UTC, alvwin commented on console_program.py
> +      if account_type == 2:
throws an exception when platform_option == 1

2024-09-06 21:36 UTC, alvwin commented on SocialService/Social/LinkedinService.py
> +            print(f"{Const.COLOR_ERROR}Company not found{Const.RESET_ALL}")
The error when the company doesn't exist doesn't work this way, better with try/catch

2024-09-07 10:37 UTC, alvwin approved these changes

2024-09-07 10:38 UTC, merged